### ISSUE TITLE
most likely due to a circular import 

### ISSUE THREAD

**Issue by yangyuwenyang** [avlmaps/AVLMaps#5]
After installing all requirements  in  readme.md, I run `python dataset/generate_dataset.py`, and got a circular import as following
```python dataset/generate_dataset.py 

Traceback (most recent call last):
File "dataset/generate_dataset.py'', line 15, in <module>
from avlmaps.utils.audio_utils import (
File "/root/AVLMaps-Project/AVLMaps/avlmaps/utils/audio_utils.py", line 20, in <module>
from avlmaps.dataloader.habitat_dataloader import VLMapsDataloaderHabitat
File "/root/AVLMaps-Project/AVLMaps/avlmaps/dataloader/habitat_dataloader.py", line11, in <module>
from avlmaps.map.map import Map
File "/root/AVLMaps-Project/AVLMaps/avlmaps/map/__init_-.py", line 10, in <module>
from .sound_map import soundMap
File "/root/AVLMaps-Project/AVLMaps/avlmaps/map/sound_map.py", Line 11, in <module>
from avlmaps.utils.audio_utils import get_level_categories, encode_audio_batch, encode_audio
ImportError: cannot import name 'get_level_categories' from partially initialized module 'avlmaps.utils.audio_utils' (most likely due to acircular i
mport) (/root/AVLMaps-Project/AVLMaps/avLmaps/utils/audio_utils.py)
```
Then, I run `python avlmaps/utils/audio_utils.py` and got 

```python 
Traceback (most recent call last):
File "avlmaps/utils/audio_utils.py", line 20, in <module>
from avlmaps.dataloader.habitat_dataloader import VLMapsDataloaderHabitat
File "/root/AVLMaps-Project/AVLMaps/avlmaps/dataloader/habitat_dataloader.py", line 11, in <module>
from avlmaps.map.map import Map
File "/root/AVLMaps-Project/AVLMaps/avLmaps/map/_ init__. py", line 10, in <module>
from .sound_map import SoundMap
File "/root/AVLMaps-Project/AVLMaps/avLmaps/map/sound_map.py", line 11, in <module>
from avlmaps.utils.audio_utils import get_level_categories, encode_audio_batch, encode_audio
File "/root/AVLMaps-Project/AVLMaps/avlmaps/utils/audio utils.py" line 20 in <module>
from avlmaps.dataloader.habitat dataloader importVLMapsDataloaderHabitat
ImportError: cannot import name 'VLMapsDataloaderHabitat, from partially initialized module'avlmaps.dataloader.habitat dataloader' (most likely due
to a circular import) (/root/AVLMaps-Project/AVLMaps/avlmaps/dataloader/habitat dataloader.py)
```

I have found names of folders, files, and functions are the same, like `from avlmaps.map.map import Map`, which maybe the reason of circular import. But I am not sure this. Is there any one have the same problem?

**Comment by yangyuwenyang** [comment]
I have change `from avlmaps.map.map import Map` to `from avlmaps.map.mapfile import Mapfunc`, but the error message is the same

**Comment by Athirakr94** [comment]
Were you able to find a fix. I am also getting same error.

**Comment by Athirakr94** [comment]
In audio_mapping_utils.py line 13, change as 
from avlmaps.utils.audio_utils import *
Now I am able to generate dataset. Hope this helps you too.

**Comment by uumennen** [comment]
Are there any other solutions? I tried the method In audio_mapping_utils.py line 13, change as
from avlmaps.utils.audio_utils import *, but I'm still getting the same error.
